name: Daily Investment Report

on:
  schedule:
    - cron: '30 05 * * *' # ตั้งเวลาทำงาน (UTC+7: 12.30 น. ของไทย)
  workflow_dispatch: # ให้เรากดปุ่มรันเองได้ด้วย

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python main.py
